[android] fix build-android scripts
This patch fixes build-nnstreamer-android scripts.
nnstreamer-release.aar file created even if ./gradlew build failed after some tasks.
So check exit code instead of aar file existance.

Signed-off-by: Yelin Jeong <yelini.jeong@samsung.com>

diff --git a/.github/workflows/android.yml b/.github/workflows/android.yml
--- a/.github/workflows/android.yml
+++ b/.github/workflows/android.yml
@@ -60,6 +60,12 @@ jobs:
         else
           bash ${{ github.workspace }}/api/java/build-nnstreamer-android.sh --target_abi=${{ matrix.abi }} --enable_nnfw=no --enable_tflite=no
         fi
+
+        result=$?
+        if [[ ${result} -ne 0 ]]; then
+          echo "NDK build failed"
+          exit 1
+        fi
     - name: Upload android library
       uses: actions/upload-artifact@v4
       with:
